apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: soc-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - soc.local
    secretName: soc-tls
  rules:
  - host: soc.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: soc-service
            port:
              number: 8080